### ISSUE TITLE
entrypoint.sh: crontab: not found

### ISSUE THREAD

**Issue by martinjuhasz** [dskaggs/docker-organize#3]
Since the latest update i get the following error when trying to start up my docker container.
Move is not invoked. 
`int.sh: 6: /entrypoint.sh: crontab: not found`

Any idea why this is happening?

**Comment by dskaggs** [comment]
I had switched the base image on that last commit to use one of the official Python images. Let me take a look and see what I can figure out.

**Comment by dskaggs** [comment]
@martinjuhasz I think I have this working correctly now. Please note the slightly different syntax of the crontab string passed in. This change is due to having to put the entire path in the crontab file. I didn't think it necessary to have to pass that entire string in every time. 

Please let me know if you continue to have issues.

**Comment by martinjuhasz** [comment]
Hm still not runnig. Getting another weird error now
```
estarting periodic command scheduler: cron[....] Stopping periodic command scheduler: cron[?25l7[1G[[32m ok [39;49m8[?12l[?25h.
tarting periodic command scheduler: cron[?25l7[1G[[32m ok [39;49m8[?12l[?25h.
```
i removed the `organize run` from the post argument cron string.

**Comment by dskaggs** [comment]
That's actually not an error. That's the console output generated when the entrypoint script is restarting the cron service after modifying the root user's crontab file. Everything I read said you didn't have to do that, but I couldn't get it to work without that restart command.

Out of curiosity, does the container continue to run for you or does it exit after you see that message?

**Comment by martinjuhasz** [comment]
Hm no, the container stops to run immediately. The only log output that i get is the one above.

**Comment by dskaggs** [comment]
Ok, that helps. I'll try to get the fix in for the v2.x version today. I've released an alpha version of v3.0 that uses Docker environment variables to pass in the cron string instead of using a post-command argument. You can see the updated docs for it in [this branch](https://github.com/dskaggs/docker-organize/tree/v3.0-alpha) and grab the tag like so `docker pull dskaggs/docker-organize:3.0-alpha`

**Comment by dskaggs** [comment]
@martinjuhasz I think I have this fixed in the 2.x version now although it's not the most elegant way of solving the problem. I tested both single run and scheduled run scenarios and both work here. There's a new tag on DockerHub for version 2.2 that, as of right now, also matches the latest tag.

Please let me know if you continue to have issues.

**Comment by martinjuhasz** [comment]
Thanks for your work on this. The container is now running continuously, still it seems the move is not invoked. At least my test file is not move after an hour or so when using `"*/10 * * * *"` as a post-command argument.

Am i missing something? I'm running `dskaggs/docker-organize:latest`
